apiVersion: v1
kind: ConfigMap
metadata:
  name: sops-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: sops-plugin
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: ["if [ -f 'secrets.enc' ]; then echo '---' > secrets.yaml && sops -d --input-type yaml --output-type yaml secrets.enc >> secrets.yaml; fi"]
      generate:
        command: ["/bin/sh", "-c"]
        args: [ "sops -d enc.${ARGOCD_APP_NAMESPACE}.values.yaml > ${ARGOCD_APP_NAMESPACE}.values.yaml && helm template -f ${ARGOCD_APP_NAMESPACE}.values.yaml . "  ]
      discover:
        fileName: "./*.enc.yaml"
# apiVersion: v1
# kind: ConfigMap
# data:
#   configManagementPlugins: |
#     - name: cmp-plugin
#       init:
#         command: ["/bin/sh", "-c"]
#         args: [ "helm init --client-only && helm dependency build" ]
#       generate:   
#         command: ["/bin/sh", "-c"]
#         args: [ "sops -d enc.${ARGOCD_APP_NAMESPACE}.values.yaml > ${ARGOCD_APP_NAMESPACE}.values.yaml && helm template -f ${ARGOCD_APP_NAMESPACE}.values.yaml . "  ]
#   repositories: |
#     - type: git
#       url: https://gitlab.com/iotops/helmcharts/gitops.git
# metadata:
#   labels:
#     app.kubernetes.io/name: cmp-plugin
#     app.kubernetes.io/part-of: argocd
#   name: cmp-plugin
#args: ["cat *.yaml | yq"]