apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-sops
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args: ["if [ -f 'secrets.enc' ]; then echo '---' > secrets.yaml && sops -d --input-type yaml --output-type yaml secrets.enc >> secrets.yaml; fi"]
      generate:
        command: ["/bin/sh", "-c"]
          args: ["cat *.yaml | yq"]
      discover:
        fileName: "./*.enc.yaml"