apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # Download tools
      initContainers:
        - name: custom-tools
          image: alpine:3.8
          command: ["/bin/sh", "-c"]
          args:
            - wget https://github.com/getsops/sops/releases/download/v3.8.0/sops-v3.8.0.linux.amd64 -O /custom-tools/sops;
              chmod a+x /custom-tools/sops;
              wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /custom-tools/jq;
              chmod a+x /custom-tools/jq;
              wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /custom-tools/yq;
              chmod +x /custom-tools/yq;

          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools

      containers:
        - name: cmp-sops
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          image: alpine/k8s:1.26.8
          imagePullPolicy: IfNotPresent
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: sops-plugin-config
            - mountPath: /tmp
              name: cmp-tmp
        
            - mountPath: /usr/local/bin/sops
              name: custom-tools
              subPath: sops
            - mountPath: /usr/local/bin/jq
              name: custom-tools
              subPath: jq
            - mountPath: /usr/local/bin/yq
              name: custom-tools
              subPath: yq
              
      volumes:
        - name: sops-plugin-config
          configMap:
            name: sops-plugin-config
        - name: custom-tools
          emptyDir: {}
        - name: cmp-tmp
          emptyDir: {}

          

      
      
          